create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Shoes', 'Shirts', 'Pants', 'Accessories')),
  price numeric not null default 0,
  image_url text,
  sizes jsonb not null default '["Free"]'::jsonb,
  stock integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  address text not null,
  items text not null,
  subtotal numeric not null default 0,
  delivery_fee numeric not null default 0,
  total numeric not null default 0,
  payment_method text not null check (payment_method in ('UPI', 'COD')),
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed'))
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public can read active products" on public.products;
drop policy if exists "Admins can manage products" on public.products;
drop policy if exists "Public can reduce visible product stock" on public.products;
drop policy if exists "Public can create orders" on public.orders;
drop policy if exists "Admins can read orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;
drop policy if exists "Admins can delete orders" on public.orders;

create policy "Public can read active products"
on public.products
for select
to anon
using (active = true and stock > 0);

create policy "Admins can manage products"
on public.products
for all
to authenticated
using (true)
with check (true);

create policy "Public can reduce visible product stock"
on public.products
for update
to anon
using (active = true)
with check (stock >= 0);

create policy "Public can create orders"
on public.orders
for insert
to anon, authenticated
with check (true);

create policy "Admins can read orders"
on public.orders
for select
to authenticated
using (true);

create policy "Admins can update orders"
on public.orders
for update
to authenticated
using (true)
with check (true);

create policy "Admins can delete orders"
on public.orders
for delete
to authenticated
using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read product images" on storage.objects;
drop policy if exists "Admins can upload product images" on storage.objects;
drop policy if exists "Admins can update product images" on storage.objects;
drop policy if exists "Admins can delete product images" on storage.objects;

create policy "Public can read product images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'product-images');

create policy "Admins can upload product images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'product-images');

create policy "Admins can update product images"
on storage.objects
for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

create policy "Admins can delete product images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'product-images');

insert into public.products (id, name, category, price, image_url, sizes, stock, active)
values
  (1, 'Heritage Automatic Watch', 'Shoes', 8999, 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80', '["40mm","42mm","44mm"]', 12, true),
  (2, 'Steel Chronograph Watch', 'Shirts', 6499, 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=900&q=80', '["42mm","44mm"]', 20, true),
  (3, 'Classic Minimal Watch', 'Pants', 3499, 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=900&q=80', '["38mm","40mm"]', 15, true),
  (4, 'Rose Gold Dress Watch', 'Shirts', 5799, 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=900&q=80', '["36mm","38mm","40mm"]', 25, true),
  (5, 'Everyday Leather Watch', 'Pants', 4299, 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=900&q=80', '["40mm","42mm"]', 10, true),
  (6, 'Premium Leather Strap', 'Accessories', 1199, 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=900&q=80', '["18mm","20mm","22mm"]', 30, true)
on conflict (id) do update
set name = excluded.name,
    category = excluded.category,
    price = excluded.price,
    image_url = excluded.image_url,
    sizes = excluded.sizes,
    stock = excluded.stock,
    active = excluded.active;
