create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Shoes', 'Shirts', 'Pants', 'Accessories')),
  price numeric not null default 0,
  image_url text,
  sizes jsonb not null default '["Free"]'::jsonb,
  stock integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  phone text not null,
  address text not null,
  items text not null,
  subtotal numeric not null default 0,
  delivery_fee numeric not null default 0,
  total numeric not null default 0,
  payment_method text not null check (payment_method in ('UPI', 'COD')),
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed'))
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

drop policy if exists "Public can read active products" on public.products;
drop policy if exists "Admins can manage products" on public.products;
drop policy if exists "Public can reduce visible product stock" on public.products;
drop policy if exists "Public can create orders" on public.orders;
drop policy if exists "Admins can read orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;

create policy "Public can read active products"
on public.products
for select
to anon
using (active = true and stock > 0);

create policy "Admins can manage products"
on public.products
for all
to authenticated
using (true)
with check (true);

create policy "Public can reduce visible product stock"
on public.products
for update
to anon
using (active = true)
with check (stock >= 0);

create policy "Public can create orders"
on public.orders
for insert
to anon, authenticated
with check (true);

create policy "Admins can read orders"
on public.orders
for select
to authenticated
using (true);

create policy "Admins can update orders"
on public.orders
for update
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read product images" on storage.objects;
drop policy if exists "Admins can upload product images" on storage.objects;
drop policy if exists "Admins can update product images" on storage.objects;
drop policy if exists "Admins can delete product images" on storage.objects;

create policy "Public can read product images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'product-images');

create policy "Admins can upload product images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'product-images');

create policy "Admins can update product images"
on storage.objects
for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

create policy "Admins can delete product images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'product-images');

insert into public.products (id, name, category, price, image_url, sizes, stock, active)
values
  (1, 'Sprint Runner Sneakers', 'Shoes', 2499, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80', '["7","8","9","10"]', 12, true),
  (2, 'Classic White Shirt', 'Shirts', 1299, 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80', '["S","M","L","XL"]', 20, true),
  (3, 'Slim Fit Denim Pants', 'Pants', 1799, 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80', '["30","32","34","36"]', 15, true),
  (4, 'Everyday Graphic Tee', 'Shirts', 899, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80', '["S","M","L","XL"]', 25, true),
  (5, 'Street Cargo Pants', 'Pants', 1999, 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80', '["30","32","34","36"]', 10, true),
  (6, 'Canvas Tote Bag', 'Accessories', 699, 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=80', '["Free"]', 30, true)
on conflict (id) do nothing;
